[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.todoist]
command = "todoist" 
class = "Todoist"
size = "50% 100%"
position = "50% 0%"
lazy = false
tiled = true

[scratchpads.notion_calendar]
command = "notion-calendar-electron" 
class = "notion-calendar-electron"
size = "50% 100%"
position = "0% 0%"
lazy = false
tiled = true
